name: My CI/CD Pipeline copy - With ProjectPlanner adaptations
run-name: ProjectPlanner CICD


on:
  push:
    branches:
      - main
    # paths-ignore:
    #   - .github/workflows/my_CICD.yml
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: false

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Python/requirements.txt

      - name: Run tests
        run: |
          cd Python/source
          pytest


###############################################
###############################################

# End of demo1

###############################################
###############################################

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t midterm:v1 ./Python/
          docker tag midterm:v1 yonioren/midterm:v1

      - name: Push Docker image
        run: docker push yonioren/midterm:v1



###############################################
###############################################

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Pull Docker image
        run: |
          docker pull yonioren/midterm:v1

      - name: Docker Run
        run: |
          docker run --rm yonioren/midterm:v1 bash -c "ls /ProjectPlanner/" > pythondir.output.txt
          cat pythondir.output.txt

      - name: Upload pythondir.output.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pythondir.output
          path: pythondir.output.txt
